#!/usr/bin/env bash
#
# local-stack-up.sh — turnkey local dev stack for fresh clones and Claude sessions.
#
# Spins up a sandbox Postgres container (port 5434, not 5432), runs Prisma
# generate+push+seed against it, generates the Python Prisma client so FastAPI
# can start, and writes a sandbox env file (.env.sandbox) the caller can source
# before running `npm run dev` or `uvicorn`. Never touches .env or .env.local.
#
# Usage:
#   scripts/local-stack-up.sh
#
# After this succeeds:
#   scripts/with-local-stack.sh npm run dev                 # Next on :3000
#   scripts/with-local-stack.sh uvicorn apps.api.src.main:app --port 8000
#   COOKIES=$(scripts/claude-login.sh)                      # grabs session cookie
#
# Teardown:
#   scripts/local-stack-down.sh
#
# Exit codes: 0 on success; non-zero on any step failure.

set -euo pipefail

# ---------- Configuration (sandbox values — safe to check into the repo) ----
CONTAINER_NAME="family-recipe-pg-sandbox"
VOLUME_NAME="family-recipe-pg-sandbox-data"
POSTGRES_IMAGE="postgres:16"
HOST_PORT="5434"                 # non-default, avoids clashing with a user's :5432 Postgres
DB_USER="family_app"
DB_PASSWORD="FamilyRecipe2025DbPass"
DB_NAME="family_recipe_dev"
FAMILY_MASTER_KEY="claude-sandbox-master-key-00"   # fixed so re-runs are deterministic
CLAUDE_TEST_USER="claude-test"
CLAUDE_TEST_PASSWORD="claude-test-password"
JWT_SECRET="sandbox-jwt-secret-not-for-production"
# ----------------------------------------------------------------------------

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env.sandbox"
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@localhost:${HOST_PORT}/${DB_NAME}"

step() { printf "\n\033[1;34m==>\033[0m %s\n" "$*"; }
info() { printf "    %s\n" "$*"; }
die()  { printf "\n\033[1;31mERROR:\033[0m %s\n" "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker not found on PATH"
command -v npx >/dev/null 2>&1 || die "npx not found on PATH (install Node.js)"
docker info >/dev/null 2>&1 || die "docker daemon is not running"

cd "$REPO_ROOT"

# ---------- Postgres container ----------------------------------------------
step "Ensure sandbox Postgres container is running (${CONTAINER_NAME} on :${HOST_PORT})"

container_state() {
  # docker inspect prints a stray blank line on missing containers even with
  # stderr muted, so check existence explicitly before asking for status.
  if docker inspect "$CONTAINER_NAME" >/dev/null 2>&1; then
    docker inspect -f '{{.State.Status}}' "$CONTAINER_NAME"
  else
    echo "missing"
  fi
}

case "$(container_state)" in
  running)
    info "container already running — reusing it"
    ;;
  exited|created|paused)
    info "container exists but stopped — starting it"
    docker start "$CONTAINER_NAME" >/dev/null
    ;;
  missing)
    info "creating container"
    docker run -d \
      --name "$CONTAINER_NAME" \
      -e "POSTGRES_USER=${DB_USER}" \
      -e "POSTGRES_PASSWORD=${DB_PASSWORD}" \
      -e "POSTGRES_DB=${DB_NAME}" \
      -p "${HOST_PORT}:5432" \
      -v "${VOLUME_NAME}:/var/lib/postgresql/data" \
      "$POSTGRES_IMAGE" >/dev/null
    ;;
  *)
    die "container in unexpected state: $(container_state)"
    ;;
esac

info "waiting for Postgres to accept connections"
for _ in $(seq 1 60); do
  if docker exec "$CONTAINER_NAME" pg_isready -U "$DB_USER" -d "$DB_NAME" -q 2>/dev/null; then
    break
  fi
  sleep 1
done
docker exec "$CONTAINER_NAME" pg_isready -U "$DB_USER" -d "$DB_NAME" -q \
  || die "Postgres did not become ready within 60s"

# ---------- Node Prisma (Next client) ----------------------------------------
step "Generate Node Prisma client + push schema"
# Running in a subshell so the exported env does not leak upward.
(
  export DATABASE_URL
  npm run --silent db:generate
  npm run --silent db:push
)

# ---------- Seed --------------------------------------------------------------
step "Seed family space + claude-test user"
(
  export DATABASE_URL
  export FAMILY_MASTER_KEY
  export CLAUDE_TEST_USER
  export CLAUDE_TEST_PASSWORD
  npm run --silent db:seed
)

# ---------- Python Prisma (FastAPI client) -----------------------------------
step "Generate Python Prisma client for FastAPI"
(
  cd "${REPO_ROOT}/apps/api"
  export DATABASE_URL
  # prisma-client-py 0.15.x (see apps/api/requirements.txt) is pinned to the
  # engine bundled with prisma CLI 5.17.0. Using the repo's newer 5.22 would
  # fail validation. Pin the CLI for this call only.
  npx --yes prisma@5.17.0 generate \
    --schema ../../prisma/schema.postgres.prisma \
    --generator clientPy >/dev/null
)

# ---------- Write .env.sandbox ------------------------------------------------
step "Write sandbox env file (${ENV_FILE})"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/local-stack-up.sh — do not edit by hand. Gitignored.
# Sandbox-only values. Source this file (or use scripts/with-local-stack.sh)
# before running \`npm run dev\` or \`uvicorn\` so the servers target the
# sandbox Postgres on :${HOST_PORT} rather than the default :5432.
DATABASE_URL="${DATABASE_URL}"
PRISMA_SCHEMA="prisma/schema.postgres.node.prisma"
JWT_SECRET="${JWT_SECRET}"
FAMILY_MASTER_KEY="${FAMILY_MASTER_KEY}"
CLAUDE_TEST_USER="${CLAUDE_TEST_USER}"
CLAUDE_TEST_PASSWORD="${CLAUDE_TEST_PASSWORD}"
EOF
chmod 600 "$ENV_FILE"

# ---------- Summary -----------------------------------------------------------
printf '\n\033[1;32m✓ local stack is up\033[0m\n\n'
cat <<EOF
  Postgres          ${CONTAINER_NAME}  (postgres:16 on localhost:${HOST_PORT})
  DATABASE_URL      ${DATABASE_URL}
  Family master key ${FAMILY_MASTER_KEY}
  Test user         ${CLAUDE_TEST_USER} / ${CLAUDE_TEST_PASSWORD}
  Sandbox env       ${ENV_FILE}  (gitignored)

Next steps:
  scripts/with-local-stack.sh npm run dev                              # Next on :3000
  scripts/with-local-stack.sh uvicorn apps.api.src.main:app --port 8000  # FastAPI on :8000
  COOKIES=\$(scripts/claude-login.sh)                                    # grab a cookie

Teardown: scripts/local-stack-down.sh
EOF
